### ISSUE TITLE
Couldn't load plugin 'sensum_eo_tools' 

### ISSUE THREAD

**Issue by enricofer** [SENSUM-project/sensum_rs_qgis#4]
I get the following exception installing plugin in qgis 2.14.1 under ubuntu 14.04 LTS

Couldn't load plugin 'sensum_eo_tools' 

StopIteration 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 281, in loadPlugin
    **import**(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/enrico/.qgis2/python/plugins/sensum_eo_tools/__init__.py", line 23, in 
    import sensum_library.config
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library/config.py", line 9, in 
    otb_path = (line[5:]+"/applications" for line in lines if "lib" in line).next()
StopIteration

Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
QGIS version: 2.14.1-Essen Essen, exported 

Python Path:
/home/enrico/.qgis2/python/plugins/GISCloudUpload
/home/enrico/.qgis2/python/plugins/processing
/home/enrico/Dropbox/dev/GeoCoding/libs
/usr/share/qgis/python
/home/enrico/.qgis2/python
/home/enrico/Dropbox/dev
/home/enrico/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
/home/enrico/.qgis2//python
/usr/share/qgis/python/plugins/fTools/tools
/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library
/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library
/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library
/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library
/home/enrico/.qgis2/python/plugins/sensum_eo_tools/sensum_library

**Comment by enricofer** [comment]
I wasn't aware of all those requirements....

**Comment by sanja7s** [comment]
Hi, I have the same issue. Could you tell me how to resolve it?
Thanks

**Comment by enricofer** [comment]
before installing plugin you have to install dependencies following plugin instructions: https://github.com/SENSUM-project/sensum_rs_qgis/blob/master/QGIS%20Plugin%20-%20Installation%20Guide.txt

**Comment by sanja7s** [comment]
thanks a lot. does this mean it works only on Windows? I have an Ubuntu system.
