### ISSUE TITLE
ValueError: Missing or corrupted OpenCV package

### ISSUE THREAD

**Issue by mchatila** [SENSUM-project/sensum_rs_qgis#5]
Hello, 

I am trying to install the QGIS package, however I keep getting the following error "ValueError: Missing or corrupted OpenCV package". Any ideas? Thanks!

**Comment by mchatila** [comment]
Here is the exact error: 

"File "/Users/file/.qgis2/python/plugins/sensum_eo_tools/sensum_library/preprocess.py", line 53, in 
    raise ValueError('Missing or corrupted OpenCV package')
ValueError: Missing or corrupted OpenCV package"

**Comment by sensum-zz** [comment]
You have to install the openCV library first. 
Please refer to the official docs
https://docs.opencv.org/3.2.0/index.html

Best, 

 M.

**Comment by mchatila** [comment]
Noted. Thanks
